### ISSUE TITLE
Claim broken

### ISSUE THREAD

**Issue by SimonLammer** [SimonLammer/packtpub-claimer#16]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "main.py", line 95, in claim
    return self.pull() + "\n"
  File "main.py", line 109, in pull
    result = user['controller'].claim_free_ebook()
  File "/code/packtpub.py", line 44, in claim_free_ebook
    last_ebook_name = self.get_last_ebook_name()
  File "/code/packtpub.py", line 39, in get_last_ebook_name
    return self.tree.xpath('//div[@id = "product-account-list"]/div[1]//div[contains(@class, "title")]/text()')[0].strip()
IndexError: list index out of range

**Comment by SimonLammer** [comment]
fixed by #17
